stages:
  - deploy

# Pages
pages:
  stage: deploy
  image: squidfunk/mkdocs-material
  environment:
    name: main
    url: https://k8s.grunty.uk
  before_script: pip install -r requirements.txt; apt install chromium
  script: mkdocs build
  artifacts:
    paths:
      - public
  needs: []
  only:
    - main
