{
 "title": "Perf Code",
 "description": "Observe Spring Boot application with three pillars of observability: Traces (Tempo), Metrics (Prometheus), Logs (Loki) on Grafana through OpenTelemetry and OpenMetrics.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(http_client_request_duration_seconds_count,service_name)"
    }
   },
   {
    "name": "code_function",
    "label": "Function",
    "query": {
     "query": "label_values(http_client_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code!=\"\"},http_response_status_code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Count",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (service_name, code_function) (http_client_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=~\"$code_function\"})",
     "legendFormat": "{{code_function}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (service_name, http_response_status_code) (http_client_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=~\"$code_function\"})",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(http_response_status_code)(http_client_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=~\"$code_function\"}) / \r\nsum by(http_response_status_code)(http_client_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=~\"$code_function\"})",
     "legendFormat": "{{ span_kind}}"
    }
   ]
  }
 ]
}