{
 "title": "Perf API",
 "description": "Observe Spring Boot application with three pillars of observability: Traces (Tempo), Metrics (Prometheus), Logs (Loki) on Grafana through OpenTelemetry and OpenMetrics.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{http_route!=\"\"}, service_name)"
    }
   },
   {
    "name": "http_route",
    "label": "http_route",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route!=\"\"}, http_route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Count",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route=~\"$http_route\"}",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route=~\"$http_route\"})",
     "legendFormat": "{{span_kind}}"
    }
   ]
  },
  {
   "title": "Total OK( 2XX )",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=~\"2.*\",http_route=~\"$http_route\"})"
    }
   ]
  },
  {
   "title": "Total Exceptions ( 3XX )",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=~\"3.*\",http_route=~\"$http_route\"})"
    }
   ]
  },
  {
   "title": "Total Exceptions ( 4XX )",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=~\"4.*\", http_route=~\"$http_route\"})"
    }
   ]
  },
  {
   "title": "Total Exceptions ( 5XX )",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=~\"5.*\",http_route=~\"$http_route\"}[1m]))"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(http_route)(http_server_request_duration_seconds_sum{service_name=\"$app_name\", http_route=~\"$http_route\"}) / \r\nsum by(http_route)(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route=~\"$http_route\"})",
     "legendFormat": "{{ span_kind}}"
    }
   ]
  },
  {
   "title": "Number of 2xx Requests",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=~\"2.*\",  http_route=~\"$http_route\"} ",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route=~\"$http_route\"}",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Number of non 2xx Requests",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code!~\"2.*\", http_route=~\"$http_route\"} ",
     "legendFormat": "{{ http_route }} "
    }
   ]
  }
 ]
}