{
 "title": "Perf DB",
 "description": "Observe Spring Boot application with three pillars of observability: Traces (Tempo), Metrics (Prometheus), Logs (Loki) on Grafana through OpenTelemetry and OpenMetrics.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(traces_span_metrics_duration_milliseconds_sum{db_sql_table!=\"\"},service_name)"
    }
   },
   {
    "name": "db_sql_table",
    "label": "Table",
    "query": {
     "query": "label_values(traces_span_metrics_duration_milliseconds_sum{service_name=\"$app_name\", db_sql_table!=\"\"},db_sql_table)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Count",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(service_name, db_sql_table ) (traces_span_metrics_duration_milliseconds_sum{service_name=\"$app_name\", db_sql_table=~\"$db_sql_table\"})",
     "legendFormat": "{{db_sql_table}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(service_name, db_sql_table) (traces_span_metrics_duration_milliseconds_sum{service_name=\"$app_name\", db_sql_table=~\"$db_sql_table\"})",
     "legendFormat": "{{db_sql_table}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(db_sql_table)(traces_span_metrics_duration_milliseconds_sum{service_name=\"$app_name\", db_sql_table=~\"$db_sql_table\"}) / \r\nsum by(db_sql_table)(traces_span_metrics_duration_milliseconds_count{service_name=\"$app_name\", db_sql_table=~\"$db_sql_table\"})",
     "legendFormat": "{{ span_kind}}"
    }
   ]
  }
 ]
}