#https://www.mkdocs.org/user-guide/deploying-your-docs/
name: ci 
on:
    push:
      tags:
        - '*'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install requirements 
        run: pip install -r requirements.txt
      - name: Deploy site
        run: mkdocs gh-deploy